package kata;

/**
 * Hello world! App auto generated by Maven archetype builder.
 */
public class App {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
